# ==============================
# Hardware Configuration
# ==============================
hardware:
  i2c_bus: 1              # I2C bus number used by the Raspberry Pi
  sensor_address: 0x03    # I2C address of the AS3935 lightning sensor
  interrupt_pin: 17       # GPIO pin number connected to the sensor's interrupt pin
  gpio_mode: 'BCM'        # GPIO numbering mode: 'BCM' or 'BOARD'

# ==============================
# Sensor Configuration
# ==============================
sensor:
  noise_floor: 2                          # Noise floor level (0-7)
  watchdog_threshold: 3                   # Watchdog threshold (0-15)
  reset_register: 0x3C                    # Register address for sensor reset
  reset_command: 0x96                     # Command to reset the sensor
  noise_floor_register: 0x01              # Register address for noise floor setting
  watchdog_threshold_register: 0x01       # Register address for watchdog threshold
  interrupt_register: 0x03                # Register address for interrupt status
  distance_register: 0x07                 # Register address for distance estimation
  noise_level_bit: 0x01                   # Bit mask for noise level too high
  disturber_bit: 0x04                     # Bit mask for disturber detected
  lightning_bit: 0x08                     # Bit mask for lightning detected
  frequency_division_ratio: 16            # Optional: Frequency division ratio
  frequency_division_register: 0x02       # Optional: Register for frequency division
  spike_rejection: 2                      # Optional: Spike rejection setting
  spike_rejection_register: 0x02          # Optional: Register for spike rejection

# ==============================
# Timing Configuration
# ==============================
timing:
  sensor_reset_delay: 0.1                 # Delay after sensor reset in seconds
  interrupt_handling_delay: 0.003         # Delay after interrupt detection in seconds
  main_loop_sleep_duration: 1             # Main loop sleep duration in seconds
  gpio_bouncetime: 500                    # GPIO bouncetime in milliseconds

# ==============================
# Logging Configuration
# ==============================
logging:
  level: 'INFO'                           # Logging level: 'DEBUG', 'INFO', 'WARNING', etc.
  format: '%(asctime)s - %(levelname)s - %(message)s'
  file: '/var/log/lightning_detection.log'  # Optional: File path to save logs

# ==============================
# Notifications Configuration
# ==============================
notifications:
  threading:
    enabled: true                         # Enable threading for notifications
    timeout: 10                           # Timeout for notification threads in seconds

  message_templates:
    lightning_detected: "⚡ Lightning detected approximately {distance} km away!"
    noise_too_high: "Warning: Noise level too high."
    disturber_detected: "Info: Disturber detected (false event)."

  slack:
    enabled: true                         # Enable Slack notifications
    channel_id: 'your-slack-channel-id'   # Slack channel ID to send messages to
    api_token_env_var: 'SLACK_API_TOKEN'  # Environment variable name for Slack API token

  twilio:
    enabled: true                         # Enable Twilio SMS notifications
    from_number: '+1234567890'            # Twilio phone number to send messages from
    to_number: '+0987654321'              # Phone number to send messages to
    account_sid_env_var: 'TWILIO_ACCOUNT_SID'  # Environment variable name for Twilio SID
    auth_token_env_var: 'TWILIO_AUTH_TOKEN'    # Environment variable name for Twilio token

# ==============================
# User Settings
# ==============================
user_settings:
  alert_threshold: 5                      # Alert threshold distance in kilometers

# ==============================
# Required Configuration Parameters
# ==============================
required_configs:
  # Sensor settings
  - ['sensor', 'noise_floor']
  - ['sensor', 'watchdog_threshold']
  - ['sensor', 'reset_register']
  - ['sensor', 'reset_command']
  - ['sensor', 'noise_floor_register']
  - ['sensor', 'watchdog_threshold_register']
  - ['sensor', 'interrupt_register']
  - ['sensor', 'distance_register']
  - ['sensor', 'noise_level_bit']
  - ['sensor', 'disturber_bit']
  - ['sensor', 'lightning_bit']

  # Hardware settings
  - ['hardware', 'i2c_bus']
  - ['hardware', 'sensor_address']
  - ['hardware', 'interrupt_pin']
  - ['hardware', 'gpio_mode']

  # Timing settings
  - ['timing', 'sensor_reset_delay']
  - ['timing', 'interrupt_handling_delay']
  - ['timing', 'main_loop_sleep_duration']
  - ['timing', 'gpio_bouncetime']

  # Notifications settings
  - ['notifications', 'message_templates', 'lightning_detected']
  - ['notifications', 'message_templates', 'noise_too_high']
  - ['notifications', 'message_templates', 'disturber_detected']
  - ['notifications', 'threading', 'enabled']
  - ['notifications', 'threading', 'timeout']

  # User settings
  - ['user_settings', 'alert_threshold']

  # Slack notifications (conditionally required if Slack is enabled)
  - ['notifications', 'slack', 'enabled']
  - ['notifications', 'slack', 'channel_id']
  - ['notifications', 'slack', 'api_token_env_var']

  # Twilio notifications (conditionally required if Twilio is enabled)
  - ['notifications', 'twilio', 'enabled']
  - ['notifications', 'twilio', 'from_number']
  - ['notifications', 'twilio', 'to_number']
  - ['notifications', 'twilio', 'account_sid_env_var']
  - ['notifications', 'twilio', 'auth_token_env_var']
